import { test, expect, type Page } from '@playwright/test'

async function addTask(page: Page, title: string, tags = '', due = '') {
  await page.getByRole('button', { name: 'New task', exact: true }).click()
  await page.getByLabel('Task', { exact: true }).fill(title)
  await page.getByLabel('Tags', { exact: true }).fill(tags)
  if (due) await page.getByLabel('Due date', { exact: true }).fill(due)
  await page.getByRole('button', { name: 'Add task', exact: true }).last().click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
}

test('queue lifecycle, focus timing, shortcuts, filtering and persistence', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.clock.install({ time: new Date('2026-09-15T09:00:00') })
  await page.goto('/')
  await expect(page.getByText('Your queue is clear.')).toBeVisible()
  await addTask(page, 'Outline the next release', 'work, planning', '2026-09-15')
  await addTask(page, 'Review the design details', 'design')
  await addTask(page, 'Book a weekend away', 'personal', '2026-09-14')

  await page.getByRole('button', { name: 'Focus Outline the next release', exact: true }).click()
  await page.clock.fastForward(65000)
  await expect(page.getByLabel('Focus time', { exact: true })).toHaveText('00:01:05')
  await page.keyboard.press('Control+Shift+Space')
  await page.clock.fastForward(30000)
  await expect(page.getByLabel('Focus time', { exact: true })).toHaveText('00:01:05')
  await page.getByRole('button', { name: 'Focus Review the design details', exact: true }).click()
  await page.clock.fastForward(120000)
  await page.keyboard.press('Control+Shift+Enter')
  await expect(page.getByText('READY WHEN YOU ARE')).toBeVisible()
  await page.getByRole('button', { name: 'Completed 1', exact: true }).click()
  await expect(page.locator('.task-title')).toHaveText(['Review the design details'])
  await page.getByRole('button', { name: 'Actions for Review the design details' }).click()
  await page.getByRole('menuitem', { name: 'Archive', exact: true }).click()
  await page.getByRole('button', { name: 'Archive 1', exact: true }).click()
  await expect(page.locator('.task-title')).toHaveText(['Review the design details'])
  await page.getByRole('button', { name: 'Restore Review the design details', exact: true }).click()
  await page.getByRole('button', { name: 'Queue 3', exact: true }).click()

  await page.getByLabel('Filter by tag').selectOption('personal')
  await expect(page.locator('.task-title')).toHaveText(['Book a weekend away'])
  await page.getByLabel('Filter by tag').selectOption('')
  await page.getByLabel('Filter by due date').selectOption('overdue')
  await expect(page.locator('.task-title')).toHaveText(['Book a weekend away'])
  await page.getByLabel('Filter by due date').selectOption('')

  await page.getByRole('button', { name: 'Outline the next release', exact: true }).click()
  await page.getByLabel('Task', { exact: true }).fill('Outline the autumn release')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await page.keyboard.press('Control+f')
  await page.getByLabel('Search tasks').fill('autumn')
  await expect(page.locator('.task-title')).toHaveText(['Outline the autumn release'])
  await page.getByRole('button', { name: 'Clear search' }).click()

  await page.getByRole('button', { name: 'Actions for Review the design details' }).click()
  await page.getByRole('menuitem', { name: 'Move up', exact: true }).click()
  await expect(page.locator('.task-title')).toHaveText(['Review the design details', 'Outline the autumn release', 'Book a weekend away'])

  await page.getByRole('button', { name: 'Focus Outline the autumn release' }).click()
  await page.clock.fastForward(10000)
  await expect(page.locator('.app-footer').getByRole('status')).toHaveText('Saved locally')
  await page.reload()
  await expect(page.getByText('FOCUS PAUSED')).toBeVisible()
  await expect(page.getByLabel('Focus time', { exact: true })).toHaveText('00:01:15')
  await page.clock.fastForward(20000)
  await expect(page.getByLabel('Focus time', { exact: true })).toHaveText('00:01:15')
  await page.getByRole('button', { name: 'Activity', exact: true }).click()
  await expect(page.locator('.activity-stats').getByText('3m', { exact: true })).toBeVisible()
  await expect(page.locator('.breakdown-list li')).toHaveCount(2)
  await page.screenshot({ path: 'test-results/activity-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Queue 3', exact: true }).click()
  await page.screenshot({ path: 'test-results/queue-desktop.png', fullPage: true })
  expect(errors).toEqual([])
})

test('narrow layout, long text, task deletion and empty filters', async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 800 })
  await page.goto('/')
  await addTask(page, 'Prepare the quarterly planning notes and review open commitments with the team', 'planning, work', '2026-09-14')
  await addTask(page, 'ReviewTomorrow'.repeat(8), 'averylongtagwithoutspaces'.repeat(3))
  await page.getByRole('button', { name: 'Start focus', exact: true }).click()
  await page.screenshot({ path: 'test-results/queue-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Activity', exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/activity-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Queue 2', exact: true }).click()
  await page.getByLabel('Search tasks').fill('not found')
  await expect(page.getByText('No matching tasks.')).toBeVisible()
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click()
  const title = 'Prepare the quarterly planning notes and review open commitments with the team'
  await page.getByRole('button', { name: `Actions for ${title}` }).click()
  await page.getByRole('menuitem', { name: 'Delete task', exact: true }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.locator('.task-title')).toHaveCount(2)
  await page.getByRole('button', { name: `Actions for ${title}` }).click()
  await page.getByRole('menuitem', { name: 'Delete task', exact: true }).click()
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page.locator('.task-title')).toHaveCount(1)
  await expect(page.getByText('READY WHEN YOU ARE')).toBeVisible()
  await page.keyboard.press('Control+k')
  await expect(page.getByRole('dialog', { name: 'New task' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('a second tab cannot overwrite the first tab', async ({ page, context }) => {
  await page.goto('/')
  await expect(page.getByText('Your queue is clear.')).toBeVisible()
  const other = await context.newPage()
  await other.goto('/')
  await expect(other.getByText('This queue is already open in another window.')).toBeVisible()
  await other.close()
})

test('permanent deletion removes every stored task title and session after reload', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-16T09:00:00') })
  await page.goto('/')
  await addTask(page, 'Private old title')
  await addTask(page, 'Keep this task')
  await page.getByRole('button', { name: 'Focus Private old title', exact: true }).click()
  await page.clock.fastForward(65000)
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await page.getByRole('button', { name: 'Private old title', exact: true }).click()
  await page.getByLabel('Task', { exact: true }).fill('Private new title')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await page.getByRole('button', { name: 'Focus Keep this task', exact: true }).click()
  await page.clock.fastForward(65000)
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await page.getByRole('button', { name: 'Actions for Private new title', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Delete task', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Delete task and history?' })).toBeVisible()
  await expect(page.getByText('This permanently removes the task and all its focus sessions', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  expect(await page.evaluate(() => localStorage.getItem('priority-queue.v1'))).toContain('Private old title')
  await page.getByRole('button', { name: 'Actions for Private new title', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Delete task', exact: true }).click()
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page.locator('.app-footer').getByRole('status')).toHaveText('Saved locally')
  const saved = await page.evaluate(() => localStorage.getItem('priority-queue.v1'))
  expect(saved).not.toContain('Private old title')
  expect(saved).not.toContain('Private new title')
  expect(saved).toContain('Keep this task')
  await page.reload()
  await expect(page.locator('.task-title')).toHaveText(['Keep this task'])
  await page.getByRole('button', { name: 'Activity', exact: true }).click()
  await expect(page.locator('.breakdown-list li')).toHaveCount(1)
  await expect(page.locator('.breakdown-list li')).toContainText('Keep this task')
})

test('privacy notice is offline and legacy cleanup is confirmed, retryable and persistent', async ({ page, context }) => {
  const state = {
    version: 1,
    tasks: [{ id: 'kept', title: 'Existing archived task', tags: [], due: '', status: 'archived', createdAt: 0, completedAt: null }],
    sessions: [
      { taskId: 'deleted', title: 'Legacy private title', start: 0, end: 1000 },
      { taskId: 'kept', title: 'Existing archived task', start: 1000, end: 2000 },
    ],
    focusId: null,
    runningSince: null,
  }
  await page.addInitScript(state => {
    if (!localStorage.getItem('priority-queue.v1')) localStorage.setItem('priority-queue.v1', JSON.stringify(state))
  }, state)
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Privacy', exact: true })).toBeVisible()
  await context.setOffline(true)
  await page.getByRole('button', { name: 'Privacy', exact: true }).click()
  const notice = page.getByRole('dialog', { name: 'Privacy notice', exact: true })
  await expect(notice).toBeVisible()
  await expect(notice.locator('.privacy-copy')).toContainText('Microsoft WebView2 diagnostics')
  await expect(notice.locator('.privacy-copy')).toContainText('required diagnostic data')
  await expect(notice.locator('.privacy-copy')).toContainText('unencrypted browser local storage')
  await expect(notice.getByText('1 retained focus session from previously deleted tasks')).toBeVisible()
  await page.screenshot({ path: 'test-results/privacy-desktop.png' })
  await page.setViewportSize({ width: 360, height: 640 })
  expect(await notice.evaluate(dialog => dialog.scrollWidth <= dialog.clientWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/privacy-mobile.png' })
  await notice.getByRole('button', { name: 'Delete retained history', exact: true }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  expect(await page.evaluate(() => localStorage.getItem('priority-queue.v1'))).toContain('Legacy private title')
  await notice.getByRole('button', { name: 'Delete retained history', exact: true }).click()
  await page.evaluate(() => {
    const originalSetItem = Storage.prototype.setItem
    let failNext = true
    Storage.prototype.setItem = function (key, value) {
      if (key === 'priority-queue.v1' && failNext) { failNext = false; throw new Error('Simulated save failure') }
      return originalSetItem.call(this, key, value)
    }
  })
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(notice.getByRole('alert')).toContainText('Save failed')
  expect(await page.evaluate(() => localStorage.getItem('priority-queue.v1'))).toContain('Legacy private title')
  await notice.getByRole('button', { name: 'Retry save', exact: true }).click()
  await expect(notice.getByRole('alert')).toHaveCount(0)
  await expect(notice.getByRole('button', { name: 'Delete retained history', exact: true })).toBeDisabled()
  await notice.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(page.locator('.app-footer').getByRole('status')).toHaveText('Saved locally')
  await context.setOffline(false)
  await page.reload()
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('priority-queue.v1')!))
  expect(saved.sessions).toEqual([state.sessions[1]])
  expect(saved.tasks).toEqual(state.tasks)
  await page.getByRole('button', { name: 'Privacy', exact: true }).click()
  await expect(notice.getByRole('button', { name: 'Delete retained history', exact: true })).toBeDisabled()
})

test('keyboard and pointer dragging reorder the queue', async ({ page }) => {
  await page.goto('/')
  await addTask(page, 'First task')
  await addTask(page, 'Second task')
  const handle = page.getByRole('button', { name: 'Reorder First task' })
  await handle.focus()
  await page.keyboard.press('Space')
  await expect(handle).toHaveAttribute('aria-pressed', 'true')
  await page.keyboard.press('ArrowDown')
  await expect(page.locator('.task-row').nth(1)).toHaveAttribute('style', /translate3d\(0px, -/)
  await page.keyboard.press('Space')
  await expect(page.locator('.task-title')).toHaveText(['Second task', 'First task'])
  const source = await page.getByRole('button', { name: 'Reorder First task' }).boundingBox()
  const target = await page.getByRole('button', { name: 'Reorder Second task' }).boundingBox()
  if (!source || !target) throw new Error('Drag handles are not visible')
  await page.mouse.move(source.x + source.width / 2, source.y + source.height / 2)
  await page.mouse.down()
  await page.mouse.move(source.x + source.width / 2, source.y - 10, { steps: 5 })
  await expect(page.locator('.task-row.dragging')).toHaveCount(1)
  await page.mouse.move(target.x + target.width / 2, target.y + target.height / 2, { steps: 10 })
  await page.mouse.up()
  await expect(page.locator('.task-title')).toHaveText(['First task', 'Second task'])
})

test('compact overlay shares the timer, advances only when running and restores the full view', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-15T09:00:00') })
  await page.goto('/')
  await addTask(page, 'Publish the infra plugin to playground')
  await addTask(page, 'Review the deployment logs')
  await addTask(page, 'Write the release notes')
  await page.getByRole('button', { name: 'Start focus', exact: true }).click()
  await page.clock.fastForward(65000)
  await page.getByRole('button', { name: 'Compact overlay (Ctrl+Shift+M)', exact: true }).click()
  await expect(page.getByRole('main', { name: 'Compact focus' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Priority Queue', exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Focus time', { exact: true })).toHaveText('00:01:05')
  await page.getByRole('button', { name: 'Pause focus', exact: true }).click()
  await page.clock.fastForward(30000)
  await expect(page.getByLabel('Focus time', { exact: true })).toHaveText('00:01:05')
  await page.getByRole('button', { name: 'Complete and load next task', exact: true }).click()
  await expect(page.locator('.overlay-title')).toHaveText('Review the deployment logs')
  await expect(page.getByRole('button', { name: 'Resume focus', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Resume focus', exact: true }).click()
  await page.clock.fastForward(10000)
  await page.getByRole('button', { name: 'Complete and load next task', exact: true }).click()
  await expect(page.locator('.overlay-title')).toHaveText('Write the release notes')
  await expect(page.getByRole('button', { name: 'Pause focus', exact: true })).toBeVisible()
  await page.clock.fastForward(15000)
  await page.getByRole('button', { name: 'Expand to full view', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Priority Queue', exact: true })).toBeVisible()
  await expect(page.getByLabel('Focus time', { exact: true })).toHaveText('00:00:15')
  await page.keyboard.press('Control+Shift+m')
  await page.keyboard.press('Control+Shift+Enter')
  await expect(page.locator('.overlay-title')).toHaveText('Queue complete')
  await expect(page.getByRole('button', { name: 'Resume focus', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Complete and load next task', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Expand to full view', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Completed 3', exact: true })).toBeVisible()
})

test('overlay is translucent, stays 88px tall and handles long task text at narrow widths', async ({ page }) => {
  await page.goto('/')
  await addTask(page, 'Publish the infra plugin to playground and verify the installation across the release environments')
  await page.getByRole('button', { name: 'Compact overlay (Ctrl+Shift+M)', exact: true }).click()
  for (const width of [420, 320]) {
    await page.setViewportSize({ width, height: 200 })
    await page.mouse.move(0, 180)
    await page.getByRole('button', { name: 'Expand to full view', exact: true }).evaluate(button => (button as HTMLButtonElement).blur())
    await expect(page.locator('.overlay-controls')).toHaveCSS('opacity', '0')
    await expect(page.locator('.focus-overlay')).toHaveCSS('height', '88px')
    await expect(page.locator('html')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.screenshot({ path: `test-results/overlay-${width}-idle.png`, omitBackground: true })
    await page.locator('.focus-overlay').hover()
    await expect(page.locator('.overlay-controls')).toHaveCSS('opacity', '1')
    await page.screenshot({ path: `test-results/overlay-${width}-hover.png`, omitBackground: true })
  }
})